// Builds the OFL attribution notice that ships next to the font files.

/**
 * Build the OFL attribution notice from the copyright string inside each font file.
 *
 * Reading it out of the `name` table rather than keeping a hand-written list means the notice cannot
 * drift out of date when fonts are added or upstream changes a copyright holder.
 */
export function renderNotice(entries) {
  const byCopyright = new Map()
  for (const entry of entries) {
    if (!entry.copyright) continue
    if (!byCopyright.has(entry.copyright)) byCopyright.set(entry.copyright, new Set())
    byCopyright.get(entry.copyright).add(entry.family)
  }

  const blocks = [...byCopyright.entries()]
    .sort((a, b) => a[0].localeCompare(b[0]))
    .map(
      ([copyright, families]) =>
        `${copyright}\n${[...families]
          .sort()
          .map((f) => `  ${f}`)
          .join('\n')}`,
    )

  // OFL clause 5 forbids modified versions from using a font's Reserved Font Name. Pull the names
  // out of the copyright strings rather than hardcoding them -- the CJK files are Adobe
  // Source-derived and reserve 'Source', which a Noto/Inter-only list would have missed.
  const reserved = new Set()
  for (const copyright of byCopyright.keys()) {
    for (const [, name] of copyright.matchAll(/Reserved Font Name[s]?\s*[:']*\s*'?([^',.]+)'?/gi)) {
      reserved.add(name.trim())
    }
  }

  return [
    'Font attribution notice for Mira',
    '================================',
    '',
    'The bundled font files in this directory are licensed under the SIL Open Font License,',
    'Version 1.1. The full license text is in OFL.txt alongside this file.',
    '',
    'Each copyright notice below is reproduced verbatim from the `name` table of the font files it',
    'covers, and is generated by tools/fonts/generate.mjs -- do not edit by hand.',
    '',
    'Reserved Font Names, per OFL clause 5 -- modified versions must not use these names:',
    ...[...reserved].sort().map((name) => `  ${name}`),
    '',
    ...blocks.flatMap((block) => [block, '']),
  ].join('\n')
}
